name = "vku-field-survey"
compatibility_date = "2026-09-08"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "vku-survey-db-v2"
database_id = "8615292d-9f25-4ffb-bbc2-166271594f8b"
