name = "vku-field-survey"
pages_build_output_dir = "dist"

# Cấu hình liên kết tự động với Cloudflare D1 Database
# Nếu bạn muốn tự động liên kết D1 bằng file này mà không cần bấm trên giao diện web:
# Hãy thay thế database_id bên dưới bằng ID lấy từ trang D1 của bạn:
#
# [[d1_databases]]
# binding = "DB"
# database_name = "vku-survey-db"
# database_id = "a6dec341-4dbd-4562-a9f3-4caa9ad09b59"
